# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Oddly Satisfying Deep Learning
author: Ujjwal Khandelwal
copyright: "2023"  # Copyright year to be placed in the footer
logo: logo.png
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
  latex_engine: pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex: true 

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

launch_buttons:
  notebook_interface: classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  colab_url: https://colab.research.google.com

# Information about where the book exists on the web
repository:
  url: https://github.com/pythonandml/dlbook  # Online location of your book

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: logo.png
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: true
  comments:
    hypothesis: true
  

